[build]
  command = "npm run build"
  publish = "out"

[context.production.environment]
  NODE_VERSION = "20"

# Handle 404s appropriately
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
